[package]
name = "life"
version = "0.1.15"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
hashable = "0.0.0"
rand = "0.10.0"
thiserror = "2.0.18"

[dev-dependencies]
pretty_assertions = "1.4.1"
